"""
thread_generator.py
────────────────────
Orchestrator utama: riset SEMUA media (website + Twitter/X + GitHub +
Telegram + Discord + Medium + CoinGecko + Reddit + Web Search)
lalu generate thread bergaya pemenang kontes via AI multi-provider.
"""

import os
import re
import json
import logging
import asyncio
import aiohttp
from bs4 import BeautifulSoup
from urllib.parse import urljoin, urlparse
from typing import Optional

from twitter_scraper import TwitterScraper
from media_researcher import MediaResearcher, detect_is_crypto
from ai_providers import generate_with_fallback, get_available_providers, PROVIDERS

logger = logging.getLogger(__name__)

# ════════════════════════════════════════════════════════════════════
# CRAFT REFERENCE
# ════════════════════════════════════════════════════════════════════

CRAFT_REFERENCE = """
Ini adalah contoh thread yang menang kontes. Baca seperti seorang penulis membaca karya terbaik —
perhatikan MENGAPA setiap kalimat bekerja, bukan APA yang ditulis.

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
THREAD REFERENSI (Fontana Ecosystem)
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

1/8
One of the biggest problems in crypto today is that many tokens don't actually do anything meaningful.

• You buy.
• You hold.
• You hope the price goes up.

That's usually the entire experience.

There's little participation, limited ecosystem growth, and no strong reason to stay engaged beyond speculation. Creating fragile communities built around price movements instead of real utility overtime.

@FontanaEcoTem takes a different approach.

Instead of launching a token first and figuring out utility later, Fontana is building an ecosystem designed around participation from the start. The idea is simple: the more you engage, the more value is created.

Went through their whitepaper, roadmap, and Twitter — a few things became clear.

Fontana is trying to build a self-sustaining digital economy that connects crypto activity, virtual economies, and real-world value.

Stay w me ✍🏿...

---
2/8
At the center of Fontana is a three-layer economic structure.

Rather than relying on one token to do everything, Fontana separates value across three distinct assets — each with a different job.

• Realityverse Points (RVP) — connects crypto activity to real-world rewards.
• LUMINA — powers the internal virtual economy inside Lumeria.
• Cerulean Sovereign Token — ultra-scarce, long-term governance layer.

This matters more than it sounds.

Most projects fail exactly here. They build one token, assign it ten jobs, and watch it collapse under its own weight. Fontana designs for separation of concerns from day one.

Less speculation. More economic flow.

---
3/8
RVP might be the most interesting piece.

It's not a governance token. Not a reward point you'll never use. It's a mechanism to connect what happens on-chain to what happens in real life.

Users earn RVP through buying activity. Those points then unlock:

• Flight tickets
• Holiday packages
• Physical goods
• Real-world experiences

The bridge between crypto and daily life is one of the hardest problems in this space. Most projects talk about it. Fontana is building the actual infrastructure for it.

That's a different conversation entirely.

---
4/8
Then there's LUMINA — the currency inside Fontana's virtual world, Lumeria.

Here's the part that caught my attention.

LUMINA isn't generated by buying. It's generated by *selling*, project participation, and ecosystem engagement. So instead of selling being an exit, it feeds back into the economy.

People use LUMINA for trading, gaming, avatar customization, P2P transactions inside Lumeria.

And when LUMINA gets spent on purchases — it burns.

Permanently.

Controlling inflation without constant manual intervention is something most token economies never figure out. This does it by design.

---
5/8
The third layer is Cerulean — Fontana's governance token. But not governance as you know it.

Most governance tokens are just purchased votes. Whoever buys the most, decides the most. It concentrates power instead of distributing it.

Cerulean Dust is earned, not bought. Through:

• Buying and selling activity
• Holding
• Social engagement
• Participating inside Lumeria

This shifts who gets influence. Not the richest wallets. The most active builders and contributors.

It's a subtle design choice. But it changes everything about how the community forms.

---
6/8
There's also an economic tax mechanism — and before you scroll past that, hear me out.

These aren't extractive taxes. Every fee collected gets redistributed:

• Back into rewards pools
• Into development funding
• Used for buybacks
• Burned to reduce supply
• Allocated to Cerulean vault reserves

Activity generates fees. Fees fund growth. Growth pulls in more participants. More participants generate more activity.

That's the flywheel. And it's baked into the architecture, not bolted on later.

---
7/8
One feature I didn't expect: the Automated Recoil Mechanism.

When heavy selling pressure pushes the price down sharply, the protocol responds automatically:

• Temporary taxes activate on sells
• Buyback mechanisms trigger
• Sell pressure absorbs into the system

The goal isn't to prevent price from ever falling. It's to stop panic from becoming a death spiral.

Markets crash because fear compounds fear. A system that self-corrects under pressure is rare. Most projects react manually — too slow, too late.

Whether this executes perfectly in practice is worth watching. But the design intent is clear: stability over volatility.

---
8/8
The roadmap runs across 7+ years. Five phases. Token launch to global adoption.

I'll be honest — long roadmaps can be theater. Anyone can write a five-year plan.

What's different here is the sequencing makes sense. Foundation first, then utility, then metaverse, then governance, then scale. Each phase builds on the last.

The Twitter activity reflects this too — consistent communication, no sudden pivots, clear focus on ecosystem building over price action.

That's the thread.

Fontana isn't trying to be another token you hold and forget. It's trying to build an economy you participate in.

Whether it gets there is an open question. But the structure is one of the more thoughtful I've read.

Website: fontanaeco.io | X: @FontanaEcoTem
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

CATATAN BAGI PENULIS — apa yang membuat thread ini bekerja:

1. PEMBUKA BUKAN TENTANG PROYEK. Kalimat pertama tentang masalah industri yang pembaca rasakan sendiri.
   Efek: pembaca merasa dipahami sebelum ditawari solusi.

2. KALIMAT PENDEK BUKAN TRIK STYLISTIC — ITU ADALAH KEPERCAYAAN DIRI.
   Penulis yang tidak yakin menulis panjang untuk terlihat pintar.
   Penulis yang yakin menulis pendek karena mereka tahu poinnya kuat.
   "Permanently." berdiri sendiri. Satu kata. Satu pukulan.

3. SETIAP TWEET MENYIMPAN SATU KEJUTAN.
   Twist, insight, atau framing yang tidak terduga. Pembaca tidak tahu apa yang akan datang selanjutnya.
   Ini yang membuat orang tidak berhenti scroll.

4. SKEPTISISME DIBANGUN KE DALAM TULISAN.
   "Long roadmaps can be theater. Anyone can write a five-year plan."
   Penulis mengakui kelemahan SEBELUM pembaca memikirkannya. Ini membangun kepercayaan.

5. FAKTA DIIZINKAN BERBICARA SENDIRI.
   Tidak ada "ini luar biasa!" — ada deskripsi mekanisme, lalu "That's a different conversation entirely."
   Penilaian datang dari pembaca, bukan penulis.

6. DATA MULTI-MEDIA DITENUN KE NARASI.
   Bukan: "Mereka punya 10k followers."
   Tapi: "Twitter activity reflects this — consistent communication, no sudden pivots."
   Data GitHub, Reddit, Discord, Telegram menjadi bukti karakter proyek — bukan laporan statistik.

7. PENUTUP JUJUR, BUKAN HYPE.
   "Whether it gets there is an open question."
   Ini justru yang paling meyakinkan. Pembaca tahu penulis tidak dibayar.
"""

VOICE_PRINCIPLES = """
PRINSIP SUARA PENULIS — INTERNALISASIKAN INI:

SUARAMU ADALAH: Analis independen yang baru saja habis tiga jam membaca docs, whitepaper, scroll Twitter,
cek GitHub, baca artikel Medium, lihat community Discord/Telegram, dan cek data on-chain.
Kamu excited karena menemukan sesuatu yang genuine menarik — bukan karena dibayar.
Kamu cukup skeptis untuk jujur, cukup terbuka untuk terkesan.

CARA BERPIKIR SEBELUM MENULIS SETIAP TWEET:
→ "Apa satu insight paling non-obvious dari bagian ini?"
→ "Bagaimana cara frame ini agar pembaca berpikir: 'oh, saya tidak pernah berpikir seperti itu'?"
→ "Apakah ada ketegangan, paradoks, atau ironi menarik di sini?"
→ "Kalimat penutup apa yang akan membuat pembaca langsung scroll ke tweet berikutnya?"
→ "Data dari media mana (GitHub stars, Discord activity, Reddit sentiment) yang paling mengejutkan?"

YANG MEMBUNUH TULISAN YANG BAIK:
- Adjektif tanpa bukti: "powerful", "innovative", "groundbreaking" — tanpa menunjukkan kenapa
- Kalimat transisi generik: "Furthermore,", "Additionally,", "In conclusion,"
- Menjelaskan obvious: jika pembaca bisa menebak kalimat berikutnya, hapus
- Hype yang tidak mau mengakui risiko: terlihat seperti PR, bukan analisis
- Bullet point yang bisa jadi kalimat: gunakan bullet HANYA ketika list benar-benar adalah list
- Melaporkan data mentah: "Community Discord: 15,000 members" → bukan insight, itu statistik

YANG MEMBUAT TULISAN HIDUP:
- Framing ulang sesuatu yang familiar dengan cara baru
- Mengakui kelemahan atau uncertainty secara jujur — lalu lanjutkan analisis
- Kalimat yang dimulai dengan kata kerja atau subjek konkret, bukan abstraksi
- Momen "zoom out" yang memberi konteks lebih besar, lalu "zoom in" ke detail spesifik
- Penutup tweet yang terasa seperti kesimpulan yang ditemukan, bukan disimpulkan
- Data cross-media yang saling mengkonfirmasi atau mengkontradiksi: "Website bilang X, tapi Reddit bilang Y"
"""


# ════════════════════════════════════════════════════════════════════
# WEB SCRAPER
# ════════════════════════════════════════════════════════════════════

class WebScraper:
    def __init__(self):
        self.headers = {
            "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 Chrome/122.0.0.0 Safari/537.36",
            "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8",
            "Accept-Language": "en-US,en;q=0.9",
        }
        self.priority_paths = [
            "whitepaper", "litepaper", "docs", "documentation", "about",
            "how-it-works", "how", "learn", "technology", "tech", "features",
            "ecosystem", "tokenomics", "token", "roadmap", "vision", "solution",
        ]

    async def fetch(self, url: str, session: aiohttp.ClientSession) -> Optional[str]:
        try:
            async with session.get(
                url, headers=self.headers,
                timeout=aiohttp.ClientTimeout(total=18),
                ssl=False, allow_redirects=True,
            ) as r:
                return await r.text(errors="ignore") if r.status == 200 else None
        except Exception as e:
            logger.warning(f"Fetch failed {url}: {e}")
            return None

    def extract(self, html: str, url: str) -> dict:
        soup = BeautifulSoup(html, "html.parser")
        for tag in soup(["script", "style", "nav", "footer", "iframe",
                          "noscript", "aside", "form", "button", "header"]):
            tag.decompose()

        title = ""
        for og in [("property", "og:title"), ("name", "twitter:title")]:
            m = soup.find("meta", attrs={og[0]: og[1]})
            if m and m.get("content"):
                title = m["content"]; break
        if not title and soup.title:
            title = (soup.title.string or "").strip()
        if not title:
            h = soup.find("h1")
            if h: title = h.get_text(strip=True)

        desc = ""
        for og in [("property", "og:description"), ("name", "description"),
                   ("name", "twitter:description")]:
            m = soup.find("meta", attrs={og[0]: og[1]})
            if m and m.get("content"):
                desc = m["content"]; break

        km = soup.find("meta", attrs={"name": "keywords"})
        keywords = km["content"] if km and km.get("content") else ""

        headings = [f"[{t.name.upper()}] {t.get_text(strip=True)}"
                    for t in soup.find_all(["h1","h2","h3","h4"])
                    if 3 < len(t.get_text(strip=True)) < 200]

        paragraphs = [p.get_text(strip=True) for p in soup.find_all("p")
                      if len(p.get_text(strip=True)) > 40]

        list_items = [li.get_text(strip=True) for li in soup.find_all("li")
                      if 20 < len(li.get_text(strip=True)) < 600]

        extra = []
        for el in soup.find_all(["div","section","article"]):
            cls = " ".join(el.get("class", []))
            eid = el.get("id", "")
            combined = (cls + " " + eid).lower()
            if any(k in combined for k in ["feature","about","how","token",
                                            "ecosystem","roadmap","benefit","why","vision"]):
                t = el.get_text(separator=" ", strip=True)
                if len(t) > 80:
                    extra.append(t[:800])

        domain = urlparse(url).netloc
        seen = set()
        links = []
        for a in soup.find_all("a", href=True):
            full = urljoin(url, a["href"])
            p = urlparse(full)
            if p.netloc == domain and full not in seen:
                path = p.path.lower()
                if any(k in path for k in self.priority_paths):
                    links.append({"url": full, "text": a.get_text(strip=True)})
                    seen.add(full)

        # Semua social links (Twitter, GitHub, Discord, Telegram, Medium, dll)
        social_platforms = [
            "twitter.com", "x.com", "t.me", "discord", "telegram",
            "github.com", "medium.com", "substack.com", "reddit.com",
            "linkedin.com", "youtube.com", "instagram.com", "facebook.com",
        ]
        socials = []
        for a in soup.find_all("a", href=True):
            href = a["href"]
            if any(s in href for s in social_platforms):
                socials.append(href)

        # Auto-detect Twitter handle
        twitter_handle = None
        for s in socials:
            m = re.search(r"(?:twitter\.com|x\.com)/([A-Za-z0-9_]+)", s)
            if m and m.group(1).lower() not in ["share","intent","home","search","i","hashtag"]:
                twitter_handle = m.group(1)
                break

        return {
            "title": title, "description": desc, "keywords": keywords,
            "headings": headings[:35], "paragraphs": paragraphs[:25],
            "list_items": list_items[:30], "extra_content": extra[:5],
            "internal_links": links[:8], "social_links": socials[:15],
            "twitter_handle": twitter_handle,
        }

    async def deep_scrape(self, base_url: str) -> dict:
        result = {"main_url": base_url, "pages": [], "twitter_handle": None, "all_social_links": []}

        async with aiohttp.ClientSession() as session:
            html = await self.fetch(base_url, session)
            if not html:
                return result

            main = self.extract(html, base_url)
            main["url"] = base_url
            main["page_type"] = "main"
            result["pages"].append(main)

            if main.get("twitter_handle"):
                result["twitter_handle"] = main["twitter_handle"]

            # Kumpulkan semua social links unik
            all_socials = set(main.get("social_links", []))

            scraped = 0
            seen_urls = {base_url}

            for link in main.get("internal_links", [])[:5]:
                if scraped >= 4:
                    break
                lurl = link["url"]
                if lurl in seen_urls:
                    continue
                await asyncio.sleep(0.4)
                sh = await self.fetch(lurl, session)
                if sh:
                    sd = self.extract(sh, lurl)
                    sd["url"] = lurl
                    sd["page_type"] = "sub"
                    result["pages"].append(sd)
                    seen_urls.add(lurl)
                    scraped += 1
                    if sd.get("twitter_handle") and not result["twitter_handle"]:
                        result["twitter_handle"] = sd["twitter_handle"]
                    all_socials.update(sd.get("social_links", []))

            # Fallback common paths
            if scraped < 2:
                parsed = urlparse(base_url)
                base = f"{parsed.scheme}://{parsed.netloc}"
                for path in ["/about","/docs","/whitepaper","/how-it-works",
                              "/technology","/ecosystem","/tokenomics","/litepaper"]:
                    if scraped >= 4:
                        break
                    cand = base + path
                    if cand in seen_urls:
                        continue
                    await asyncio.sleep(0.4)
                    ch = await self.fetch(cand, session)
                    if ch:
                        cd = self.extract(ch, cand)
                        cd["url"] = cand
                        cd["page_type"] = "fallback"
                        result["pages"].append(cd)
                        seen_urls.add(cand)
                        scraped += 1
                        all_socials.update(cd.get("social_links", []))

            result["all_social_links"] = list(all_socials)

        return result


# ════════════════════════════════════════════════════════════════════
# THREAD GENERATOR (ORCHESTRATOR)
# ════════════════════════════════════════════════════════════════════

class ThreadGenerator:
    def __init__(self):
        available = get_available_providers()
        if not available:
            raise ValueError(
                "Tidak ada API key yang dikonfigurasi. "
                "Isi minimal satu di .env: GROQ_API_KEY, DEEPSEEK_API_KEY, atau OPENAI_API_KEY"
            )
        self.web_scraper = WebScraper()
        self.twitter_scraper = TwitterScraper()
        self.media_researcher = MediaResearcher()

    def compile_web_research(self, data: dict) -> str:
        parts = []
        for page in data.get("pages", []):
            ltype = {"main":"HALAMAN UTAMA","sub":"SUB-PAGE",
                     "fallback":"COMMON PATH"}.get(page.get("page_type",""),"PAGE")
            parts.append(f"\n{'='*55}\n{ltype}: {page.get('url','')}\n{'='*55}")

            for key, label in [("title","TITLE"),("description","DESCRIPTION"),("keywords","KEYWORDS")]:
                if page.get(key):
                    parts.append(f"{label}: {page[key]}")

            if page.get("social_links"):
                parts.append(f"SOCIAL LINKS: {', '.join(page['social_links'][:6])}")

            if page.get("headings"):
                parts.append("\nSTRUKTUR HALAMAN:")
                parts.extend(page["headings"][:20])

            if page.get("paragraphs"):
                parts.append("\nKONTEN PARAGRAF:")
                for p in page["paragraphs"][:15]:
                    parts.append(f"  → {p[:400]}")

            if page.get("list_items"):
                parts.append("\nFITUR/POIN-POIN:")
                for li in page["list_items"][:20]:
                    parts.append(f"  • {li[:300]}")

            if page.get("extra_content"):
                parts.append("\nSEKSI KHUSUS:")
                for ec in page["extra_content"]:
                    parts.append(f"  [{ec[:500]}]")

        return "\n".join(parts)

    def create_prompt(
        self,
        web_research: str,
        twitter_research: str,
        media_research: str,
        url: str,
        twitter_handle: str,
        lang: str,
    ) -> str:

        if lang == "indonesia":
            lang_directive = """BAHASA: Tulis dalam Bahasa Indonesia yang benar-benar natural — seperti seseorang yang cerdas dan banyak baca, bukan terjemahan dari Inggris. Istilah teknis crypto/web3 tetap dalam bahasa Inggris. Hindari kalimat terjemahan literal yang terasa kaku."""
        else:
            lang_directive = """LANGUAGE: Write in English. Not formal English. The English of someone smart who reads a lot but talks like a real person."""

        twitter_block = (
            f"TWITTER/X DATA — @{twitter_handle}:\n{twitter_research}\n\n"
            f"Gunakan data Twitter bukan sebagai laporan, tapi sebagai bukti karakter proyek. "
            f"Tone komunikasi mereka, konsistensi posting, jenis announcement yang mereka buat — "
            f"semua itu cerita tentang siapa tim ini sebenarnya."
            if twitter_research and twitter_handle
            else "Twitter data: tidak tersedia. Fokus pada riset website dan media lain."
        )

        media_block = (
            f"DATA RISET MULTI-MEDIA (GitHub, Telegram, Discord, Medium, Reddit, CoinGecko, Web):\n{media_research}\n\n"
            f"PENTING: Gunakan data ini untuk cross-validate klaim website. "
            f"Jika GitHub aktif tapi website minim info — GitHub adalah bukti tim bekerja. "
            f"Jika Discord sepi tapi klaim besar — itu sinyal yang jujur harus disebutkan. "
            f"Data multi-media adalah cara kamu membedakan antara proyek sungguhan dan proyek theater."
            if media_research
            else ""
        )

        return f"""Kamu seorang penulis thread Twitter yang tulisannya selalu menang kontes — bukan karena mengikuti formula, tapi karena kamu menulis seperti manusia yang benar-benar peduli dengan apa yang kamu tulis.

Baca referensi craft ini dengan seksama. Pelajari MENGAPA setiap kalimat bekerja:

{CRAFT_REFERENCE}

Prinsip suara yang harus kamu internalisasikan:

{VOICE_PRINCIPLES}

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
TUGASMU: Tulis thread tentang project di {url}
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

DATA RISET WEBSITE (jangan mengarang apapun yang tidak ada di sini):
{web_research}

{twitter_block}

{media_block}

{lang_directive}

SEBELUM MENULIS, lakukan ini dalam kepalamu:
1. Baca SEMUA data riset di atas — website, Twitter, GitHub, Telegram, Discord, Reddit, dll.
2. Tanya: "Apa yang konsisten di semua channel? Apa yang kontradiktif?"
3. Tanya: "Apa satu hal paling menarik yang hanya terlihat jika kamu riset lintas media?"
4. Tanya: "Apa masalah industri yang project ini coba jawab — yang pembaca bisa relate secara personal?"
5. Tanya: "Apa insight counter-intuitive atau framing baru yang bisa saya tawarkan?"
6. Baru mulai menulis. Jangan dari tweet 1 — mulai dari insight terkuat, lalu bangun backward ke hook.

PRINSIP PENULISAN:

→ SETIAP TWEET PUNYA SATU IDE UTAMA DAN SATU MOMEN KEJUTAN
→ KALIMAT PENDEK ADALAH KEPERCAYAAN DIRI
→ SKEPTISISME ADALAH KREDIBILITAS — akui kelemahan sebelum pembaca memikirkannya
→ DATA MULTI-MEDIA ADALAH KARAKTER, BUKAN STATISTIK
   Bukan: "Discord 15,000 members, GitHub 200 stars."
   Tapi: "Yang menarik: GitHub mereka punya 200+ contributors aktif — ini bukan proyek satu orang."
→ BULLET POINT HANYA KETIKA LIST MEMANG LIST
→ PEMBUKA BUKAN TENTANG PROYEK — mulai dari masalah yang pembaca rasakan
→ PENUTUP JUJUR, BUKAN TRIUMPHANT

ATURAN TEKNIS:
- Numbering: "1/N" — hitung total tweet dulu, baru tulis
- Minimal 7, maksimal 12 tweets
- Tweet pertama diakhiri dengan "Stay w me 🧵..." atau variasi natural yang sama-sama mengundang
- Tweet terakhir: refleksi jujur + website + @TwitterHandle jika ada
- DILARANG KERAS mengarang data, angka, atau kutipan yang tidak ada di riset
- Maksimal 2 emoji per tweet, hanya jika memang menambah, bukan menghias
- Jangan gunakan kata: "amazing", "revolutionary", "game-changing", "groundbreaking"

RETURN ONLY VALID JSON — no markdown fences, no explanation, nothing before the opening brace:
{{
  "project_name": "Nama Project",
  "twitter_handle": "@handle_atau_kosong",
  "total_tweets": 9,
  "tweets": [
    "1/9\\nIsi tweet pertama\\n\\nDengan baris baru seperti ini",
    "2/9\\nIsi tweet kedua",
    "3/9\\nDan seterusnya..."
  ]
}}
"""

    async def generate_thread(
        self,
        url: str,
        twitter_handle: str = "",
        lang: str = "english",
        provider: str = "groq",
    ) -> dict:
        try:
            # ── Step 1: Scrape website ──────────────────────────────
            logger.info(f"[ThreadGenerator] Scraping website: {url}")
            web_data = await self.web_scraper.deep_scrape(url)

            if not web_data.get("pages"):
                return {"success": False, "error": "Tidak bisa mengakses website."}

            web_research = self.compile_web_research(web_data)
            if len(web_research) < 150:
                return {"success": False,
                        "error": "Konten terlalu sedikit. Coba URL docs/whitepaper project."}

            # Deteksi nama project dari halaman utama
            first_page = web_data["pages"][0]
            project_name_raw = first_page.get("title", self._domain(url))

            # ── Step 2: Twitter ─────────────────────────────────────
            detected_handle = web_data.get("twitter_handle", "")
            final_handle = twitter_handle or detected_handle or ""

            twitter_research = ""
            twitter_data = {}
            if final_handle:
                logger.info(f"[ThreadGenerator] Scraping Twitter: @{final_handle}")
                twitter_data = await self.twitter_scraper.research_account(final_handle)
                if twitter_data.get("success"):
                    twitter_research = self.twitter_scraper.format_for_research(twitter_data)
                    logger.info(f"[ThreadGenerator] Twitter OK: {len(twitter_research)} chars")
                else:
                    twitter_research = f"[Twitter @{final_handle}: tidak bisa diakses]"
            else:
                logger.info("[ThreadGenerator] No Twitter handle — skipping")

            # ── Step 3: Multi-media research ────────────────────────
            logger.info("[ThreadGenerator] Starting multi-media research...")
            is_crypto = detect_is_crypto(web_data)
            all_social_links = web_data.get("all_social_links", [])

            # Filter out Twitter links (sudah dihandle di step 2)
            non_twitter_links = [
                l for l in all_social_links
                if "twitter.com" not in l and "x.com" not in l
            ]

            media_data = await self.media_researcher.research_all(
                social_links=non_twitter_links,
                project_name=project_name_raw,
                is_crypto=is_crypto,
            )
            media_research = self.media_researcher.compile_for_prompt(media_data)
            logger.info(f"[ThreadGenerator] Media research done: {list(media_data.keys())}")

            # ── Step 4: Generate dengan AI ─────────────────────────
            logger.info(f"[ThreadGenerator] Generating with provider: {provider}")
            prompt = self.create_prompt(
                web_research, twitter_research, media_research,
                url, final_handle, lang
            )

            system_prompt = (
                "Kamu adalah penulis dengan suara khas — "
                "berpikir seperti jurnalis investigatif, menulis seperti essayist yang peduli craft. "
                "Setiap kalimat harus bisa menjawab: mengapa kalimat ini harus ada? "
                "Tidak pernah mengarang data. "
                "Return ONLY valid JSON — tidak ada teks sebelum { maupun sesudah }."
            )

            raw, provider_used = await generate_with_fallback(
                prompt=prompt,
                system=system_prompt,
                preferred_provider=provider,
            )
            data = self._parse_json(raw)

            if not data or "tweets" not in data:
                logger.error(f"JSON parse failed. Raw: {raw[:300]}")
                return {"success": False, "error": "Gagal parse response AI. Coba lagi."}

            tweets = data["tweets"]
            total = len(tweets)

            # Fix numbering
            fixed = []
            for i, t in enumerate(tweets, 1):
                body = re.sub(r"^\d+/\d+\s*\n?", "", t).strip()
                fixed.append(f"{i}/{total}\n{body}")

            provider_info = PROVIDERS.get(provider_used, {})

            # Rangkuman media yang berhasil diambil
            media_sources_used = list(media_data.keys())

            return {
                "success": True,
                "project_name": data.get("project_name", self._domain(url)),
                "twitter_handle": final_handle,
                "twitter_success": twitter_data.get("success", False),
                "twitter_source": twitter_data.get("source", ""),
                "tweets": fixed,
                "tweet_count": total,
                "url": url,
                "provider_used": provider_used,
                "provider_name": provider_info.get("name", provider_used),
                "provider_emoji": provider_info.get("emoji", "🤖"),
                "provider_model": provider_info.get("model", ""),
                "media_sources": media_sources_used,
                "is_crypto": is_crypto,
            }

        except Exception as e:
            logger.error(f"generate_thread error: {e}", exc_info=True)
            return {"success": False, "error": str(e)}

    def _parse_json(self, raw: str) -> Optional[dict]:
        for fn in [
            lambda: json.loads(raw),
            lambda: json.loads(re.sub(r"^```(?:json)?\s*|\s*```$", "", raw, flags=re.MULTILINE).strip()),
            lambda: json.loads(re.search(r"\{[\s\S]*\}", raw).group()) if re.search(r"\{[\s\S]*\}", raw) else (_ for _ in ()).throw(ValueError()),
        ]:
            try:
                r = fn()
                if r: return r
            except Exception:
                continue
        return None

    def _domain(self, url: str) -> str:
        netloc = urlparse(url).netloc.replace("www.", "")
        return netloc.split(".")[0].capitalize()
